name=home-assistant-integration-extended
version=2.1.1
author=Dawid Chyrzynski <dev@chyrzynski.pl>
maintainer=Kyle Johnson
sentence=Extended Home Assistant MQTT integration for Arduino
paragraph=Lightweight library that provides easy to use API for integrating your Arduino/ESP based device with Home Assistant. Includes option to use entity_categories for sensors.
category=Communication
url=https://github.com/pkscout/arduino-home-assistant
architectures=*
depends=PubSubClient
